version: '3.1'

services:
  groningenonbeperkt.netcore.website:
    image: groningenonbeperkt.netcore.website
    secrets:
      - dbsecret
    container_name: app
    build:
      context: .
      dockerfile: ./GroningenOnbeperkt.NetCore.Website/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT="Production"
    networks:
      - webapp
      - database
  web:
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    container_name: proxy
    ports:
      - "80:80"
    networks:
      - routing
      - webapp
  osrm:
    image: osrm.routing
    container_name: osrm
    build:
      context: ./OSRM/backend
      dockerfile: Dockerfile
    networks:
      - routing
  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: groningenonbeperkt
      MYSQL_USER: groningenonbeperkt
      MYSQL_PASSWORD: groningenonbeperkt

    networks:
      - database
networks:
  webapp:
  routing:
  database:
secrets:
  dbsecret:
    file: ./dbsecret.txt
